name: 'Danger'
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  build:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v2
        with:
          fetch-depth: 0
      - run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
