name: 'Danger'
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  build:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v3 # v3 # v2
        with:
          fetch-depth: 0
      - run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
