name: 'Danger'
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review, labeled, unlabeled]


permissions:
  contents: write
  pull-requests: write
  statuses: write # Required for the danger action to commit a message on the PR.
jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: getsentry/github-workflows/danger@17cc15eb58ea3687cd8f2714a4192dcee4aa09ef
