name: 'Sample Build'

on:
  workflow_call:
    inputs:
      dependency_cache_key:
        required: true
        type: string
      build_cache_key:
        required: true
        type: string

env:
  CACHED_DEPENDENCY_PATHS: |
    ${{ github.workspace }}/node_modules
  CACHED_BUILD_PATHS: |
    ${{ github.workspace }}/dist
  BUILD_CACHE_KEY: ${{ inputs.build_cache_key }}


permissions:
  contents: write
  pull-requests: write
jobs:
  ready-to-merge-gate:
    name: Ready-to-merge gate
    uses: ./.github/workflows/ready-to-merge-workflow.yml
    with:
      is-pr: ${{ github.event_name == 'pull_request' }}
      labels: ${{ toJson(github.event.pull_request.labels) }}
  job_sample_build:
    name: Sample Build (${{ matrix.bump }})
    runs-on: macos-latest
    needs: ready-to-merge-gate
    strategy:
      matrix:
        include:
          - bump: 'v6'
            SAMPLE_DIR: 'example/ionic-angular-v6'
            JAVA_VERSION: '17'
          - bump: 'v7'
            SAMPLE_DIR: 'example/ionic-angular-v7'
            JAVA_VERSION: '21'
          - bump: 'v8'
            SAMPLE_DIR: 'example/ionic-angular-v8'
            JAVA_VERSION: '22'
          - bump: 'sample-vue'
            SAMPLE_DIR: 'example/ionic-vue3'
            JAVA_VERSION: '22'
    steps:
      - name: Check out current commit (${{ github.sha }})
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: corepack enable
      - name: Set up Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v5
      - name: Check dependency cache
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # V5.0.2
        with:
          path: ${{ env.CACHED_DEPENDENCY_PATHS }}
          key: ${{ inputs.dependency_cache_key }}
      - name: Check build cache
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # V5.0.2
        with:
          path: ${{ env.CACHED_BUILD_PATHS }}
          key: ${{ env.BUILD_CACHE_KEY }}
      - name: Install yalc
        run: yarn  global add yalc
      - name: Install Ionic
        run: yarn  global add @ionic/cli

      - name: Download Sentry Capacitor package
        uses: actions/download-artifact@v4
        with:
          name: yalc-package
          path: ~/.yalc/packages/@sentry/capacitor/

      - name: Publish test broken node.
        working-directory: example/broken_node_module
        run: |
          yarn install
          yarn build
          yalc publish

      - name: Build Sample ${{ matrix.bump }}
        run: yarn run bump:${{ matrix.bump }}

      - name: Set up Java ${{ matrix.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.JAVA_VERSION }}

      - name: Make gradlew executable
        working-directory: ${{ matrix.SAMPLE_DIR }}/android
        run: chmod +x ./gradlew

      - name: Configure Android build compatibility
        working-directory: ${{ matrix.SAMPLE_DIR }}/android
        run: |
          echo "android.useFullClasspathForDexingTransform=true" >> gradle.properties
          echo "android.enableR8.fullMode=false" >> gradle.properties

      - name: Android build (Gradle)
        working-directory: ${{ matrix.SAMPLE_DIR }}/android
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.bump }}-android-apk
          if-no-files-found: warn
          path: |
            ${{ matrix.SAMPLE_DIR }}/android/app/build/outputs/apk/debug/*.apk

      - name: Install xcpretty
        run: sudo gem install xcpretty --no-document

      - name: iOS pod install
        working-directory: ${{ matrix.SAMPLE_DIR }}/ios/App
        run: pod install --repo-update

      - name: Select iOS Simulator
        run: |
          SIMULATOR_NAME=$(xcrun simctl list devices available | grep -oE 'iPhone [0-9]+' | head -n1)
          echo "Selected iOS Simulator: $SIMULATOR_NAME"
          echo "SIMULATOR_NAME=$SIMULATOR_NAME" >> $GITHUB_ENV

      - name: iOS build (xcodebuild)
        working-directory: ${{ matrix.SAMPLE_DIR }}/ios/App
        run: |
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -configuration Debug \
                     -sdk iphonesimulator \
                     -destination "platform=iOS Simulator,name=$SIMULATOR_NAME" \
                     build | xcpretty && exit ${PIPESTATUS[0]}

      - name: Upload iOS build logs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.bump }}-ios-build-logs
          if-no-files-found: warn
          path: |
            ~/Library/Logs/Diagnostics/*
